// Generated by scripts/build-calendar-data.mjs from the events form responses. Do not edit by hand.
window.SFX_CALENDAR = {
  months: [
    { "id": "2026-10", "label": "October 2026" },
    { "id": "2026-11", "label": "November 2026" },
    { "id": "2026-12", "label": "December 2026" }
  ],
  categories: [
    { "id": "core", "label": "Standing Order" },
    { "id": "exp", "label": "Experimental" },
    { "id": "fruit", "label": "Heavy Fruit" },
    { "id": "creamery", "label": "The Creamery" },
    { "id": "collab", "label": "Collab" },
    { "id": "release", "label": "New release" },
    { "id": "lto", "label": "Wholesale $1 LTO" },
    { "id": "event", "label": "Event" },
    { "id": "burger", "label": "Food" }
  ],
  items: [
    { "name": "Mixed Berry Waffle Whip Heavy Fruit", "cat": "fruit", "start": "2026-09-25", "end": "2026-10-23" },
    { "name": "$1 Premium Rice Lager LTO", "cat": "lto", "start": "2026-09-27", "end": "2026-10-24", "slug": "premium-rice-lager" },
    { "name": "The Creamery Pumpkin Pie", "cat": "creamery", "date": "2026-10-02" },
    { "name": "Oktoberfest", "cat": "event", "date": "2026-10-03" },
    { "name": "Exp. DIPA #2", "cat": "exp", "date": "2026-10-08" },
    { "name": "Dreamscape", "cat": "core", "date": "2026-10-13", "slug": "dreamscape-2026" },
    { "name": "Exp. #86 NZ Fresh Hop", "cat": "exp", "date": "2026-10-15", "slug": "experimental-ipa-86" },
    { "name": "BC Craft Beer Awards", "cat": "event", "date": "2026-10-16" },
    { "name": "Cask Days Toronto", "cat": "event", "start": "2026-10-16", "end": "2026-10-18" },
    { "name": "Brewchacho' Negra", "cat": "release", "date": "2026-10-21", "slug": "brewchacho-negra" },
    { "name": "Key Lime Pie Heavy Fruit", "cat": "fruit", "start": "2026-10-23", "end": "2026-11-20" },
    { "name": "$1 Easy Tiger LTO", "cat": "lto", "start": "2026-10-25", "end": "2026-11-21", "slug": "easy-tiger" },
    { "name": "$1 Happyness LTO", "cat": "lto", "start": "2026-10-25", "end": "2026-11-21", "slug": "happyness" },
    { "name": "Exp Dipa #3", "cat": "exp", "date": "2026-10-28" },
    { "name": "Candyland", "cat": "release", "date": "2026-10-29" },
    { "name": "Petaluma", "cat": "release", "date": "2026-10-29" },
    { "name": "Exp #87", "cat": "exp", "date": "2026-11-06" },
    { "name": "Wills Collab", "cat": "collab", "date": "2026-11-12" },
    { "name": "Billies Craft Beer Fest", "cat": "event", "start": "2026-11-13", "end": "2026-11-14" },
    { "name": "Christmas IPA", "cat": "release", "date": "2026-11-17" },
    { "name": "The Creamery Strawberry Cheesecake", "cat": "creamery", "date": "2026-11-18" },
    { "name": "$1 Colour & Shape LTO", "cat": "lto", "start": "2026-11-22", "end": "2026-12-26", "slug": "colour-and-shape" },
    { "name": "$1 Premium Rice Lager", "cat": "lto", "start": "2026-11-22", "end": "2026-12-26", "slug": "premium-rice-lager" },
    { "name": "Exp #88", "cat": "exp", "date": "2026-11-26" }
  ],
  recurring: [
    { "name": "Burger Day", "cat": "burger", "weekdays": [6] }
  ]
};
