// Generated by scripts/build-calendar-data.mjs from the events form responses. Do not edit by hand.
window.SFX_CALENDAR = {
  months: [
    { "id": "2026-09", "label": "September 2026" },
    { "id": "2026-10", "label": "October 2026" },
    { "id": "2026-11", "label": "November 2026" }
  ],
  categories: [

  ],
  items: [

  ],
  recurring: [

  ]
};
